#define DISABLED -1

#define TEX_NUM 10

#define FOG_LINEAR 0
#define FOG_EXPONENTIAL 1
#define FOG_EXPONENTIAL2 2 

#define LIGHT_NUM 1

#define DIRECTIONAL_LIGHT 0
#define POINT_LIGHT 1
#define SPOT_LIGHT 2